name: keyboard_visibility_example
description: Keyboard visibility example

version: 1.0.0+2

environment:
  sdk: ">=2.9.0-14.1.beta <3.0.0"
  flutter: ">=1.19.0-4.3.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_visibility:
    path: ../

flutter:
  uses-material-design: true
