name: keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 0.5.7
author: progrand <progrand@gmail.com>
homepage: https://github.com/PROGrand/flutter_keyboard_visibility/tree/master

environment:
  sdk: ">=2.9.0-14.1.beta <3.0.0"
  flutter: ">=1.19.0-4.3.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.adee42.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin

module:
  androidX: true